#!/bin/sh
set -e
set -u

control_dir="$(dirname $0)"
. "$control_dir/config"
# Not yet ready
#. "$genapp_dir/env"

# Launch the app
cd $app_dir/app

echo "Executing Rake Tasks $args..."
exec bash -c "bundle exec rake $args"